---
fontsize: 11pt
geometry: margin=1in
header-includes:
   - \setlength\parindent{14pt}
   - \usepackage{caption}
   - \usepackage{tipa}
output: pdf_document
---

\begin{center}
\large{\textbf{Análisis de produccion}}\\ [1ex]
\normalsize{\emph{Fonética y comunicación oral}} \\ [1ex]
\normalsize{otoño 2015}
\end{center}




\noindent Para este trabajo práctico vas a empezar a desarrollar tus dotes como lingüista. Utilizando las dos grabaciones que tienes (del comienzo y del final del semestre), vas a realizar un análisis del progreso de tu pronunciación durante las últimas 14 semanas. A continuación tienes algunos temas que puedes tratar en el análisis:

\begin{itemize}
	\setlength\itemsep{-.2em}
	\item la schwa \textipa{[\textschwa]}
	\item el encadenamiento 
	\item las oclusivas sordas
	\item las oclusivas sonoras
	\item los procesos de asimilación
	\item las vibrantes
\end{itemize}

\noindent No tienes que hablar de cada cosa de la lista y puedes hablar de cosas que no aparezcan en la lista. Hay muchas posibilidades. Tienes libertad absoluta y puedes escoger lo que sea más relevante para **tu** pronunciación. Dicho eso, tienes que entregar un ensayo que cuente con las siguientes características:

\begin{enumerate}
	\setlength\itemsep{-.2em}
	\item Una descripción de tu historial lingüística
	\item Un análisis general de la primera grabación
	\item Un análisis de al menos tres aspectos de la segunda grabación
	\item Algunos aspectos de tu pronunciación que aún tengas que mejorar y un plan para hacerlo
\end{enumerate}

\noindent Algunos detalles más acerca del ensayo.

\begin{itemize}
	\setlength\itemsep{-.2em}
	\item Una extensión de entre 500-700 palabras
	\item Fuente de 12pt, times new roman, interlineado sencillo
	\item Márgenes de 1 pulgada
	\item Formato PDF
	\item Nombre de archivo: `apellido\_analisis\_fon2015.pdf' (ej. casillas\_analisis\_fon2015.pdf)
	\item Se entrega por email el día 15 de diciembre antres de las 10:30 am
\end{itemize}



\clearpage

\noindent Esquema

\begin{enumerate}
	\setlength\itemsep{-.2em}
	\item Intro - historial lingüístico (1 párrafo)
	\begin{itemize}
		\setlength\itemsep{-.2em}
		\item Nombre
		\item Edad
		\item Lugar de nacimiento
		\item Primera lengua (variedad)
		\item Lenguas que hablas
		\item Cantidad de tiempo que llevas estudiando español
		\item Variedad del español que hablas
	\end{itemize}
	\item Un análisis general de la primera grabación (1 párrafo)
	\begin{itemize}
		\setlength\itemsep{-.2em}
		\item la schwa \textipa{[\textschwa]}
		\item el encadenamiento 
		\item las oclusivas sordas
		\item las oclusivas sonoras
		\item los procesos de asimilación
		\item las vibrantes
		\item etc.
	\end{itemize}
	\item Un análisis de al menos tres aspectos de la segunda grabación (3 párrafos)
	\begin{itemize}
		\setlength\itemsep{-.2em}
		\item 1 párrafo cada tema
		\item Explicar tema lingüístico 
		\item Describir cómo tu pronunciación difiere de la de un nativo
		\item Comparar tu pronunación (antes/después)
		\item Citar ejemplos concretos (ej. en el minuto 2:34 de la segunda grabación...)
	\end{itemize}
	\item Conclusión (1 párrafo)
	\begin{itemize}
		\setlength\itemsep{-.2em}
		\item Evaluación general de tu progreso
		\item Cosas que puedas mejorar en el futuro
		\item Cómo las vas a mejorar
	\end{itemize}
\end{enumerate}


